config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Routes for Posts
  resources :posts do
    # Nested routes for Comments under Posts
    resources :comments, only: [:create, :update] do
      member do
        get 'edit_comment'
        patch 'update_comment'
      end
    end
  end

  resources :comments, only: :destroy

  resources :contact, only: [:new, :create]

  # Routes for Plants
  resources :plants do
    # Nested routes for Tips under Plant
    resources :tips, only: [:create] do
      member do
        get 'edit_tip'
        patch 'update_tip'
      end
    end
    resources :neighbours, only: [:create]
  end

  # Routes for Lists
  resources :lists do
    # Nested routes for PlantLists under Lists
    resources :plant_lists, only: [:create] do
      member do
        get 'edit_plant_list'
        patch 'update_plant_list'
      end
    end
  end

  # Routes for Tips (outside the nested context if needed)
  resources :tips, only: [:index, :show, :update, :destroy]
  # Routes for PlantLists (outside the nested context if needed)
  resources :plant_lists, only: [:index, :show, :update, :destroy]
  # Routes for Neighbours
  resources :neighbours, only: [:index, :show, :update, :destroy]

  root to: "pages#home"

  get 'a-propos', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  get 'recrutement', to: 'pages#recrutement'
  get 'calendrier', to: 'calendriers#index'
  get 'telecharger', to: 'calendriers#download'
  get 'mentions-legales', to: 'pages#mentions_legales'
  get 'plant-finder', to: 'pages#plant_finder'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mt-3">
  <div class="container">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-center py-2 mb-3" style="background-color: #DAF1DF; border-radius: 10px;">
      <div class="text-center text-dark p-3">
        Inscrivez-vous à notre lettre d'information
      </div>

      <div class="d-flex flex-row gap-2 w-100 p-3">
        <input id="newsletter" type="text" class="form-control rounded-pill p-2" placeholder="Votre email">
        <button class="btn btn-success text-white rounded-pill p-2" type="button">S'inscrire</button>
      </div>

      <div class="d-flex justify-content-center align-items-center p-3">
        <a href="https://www.instagram.com/when_toplant/" class="mx-2"><i class="fab fa-instagram fa-xl"></i></a>
        <a href="https://www.facebook.com/profile.php?id=61562363171250" class="mx-2"><i class="fab fa-facebook fa-xl"></i></a>
        <a href="https://www.youtube.com/@WhenToPlant" class="mx-2"><i class="fab fa-youtube fa-xl"></i></a>
        <a href="https://twitter.com/whentoplant" class="mx-2"><i class="fab fa-twitter fa-xl"></i></a>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center py-3 bg-success">
    <%= image_tag "when to plant blanc.png", style: "width:189px; height:50px;" %>
  </div>

  <div class="bg-success pb-1 mb-1">
    <div class="w-75 d-flex justify-content-center m-auto flex-wrap">
      <div class="p-3 text-center">
        <%= link_to "Contact", contact_index_path, class: "text-white text-decoration-none" %>
      </div>
      <div class="p-3 text-center">
        <%= link_to "Recrutement", recrutement_path, class: "text-white text-decoration-none" %>
      </div>
      <div class="p-3 text-center">
        <%= link_to "Mentions légales", mentions_legales_path, class: "text-white text-decoration-none" %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-xl navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid bg-success">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "when to plant blanc.png", style: "width:169px; height:40px; margin-bottom:25px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center bg-success" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Catégories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/plants?query=légumes">Légumes</a>
            <a class="dropdown-item" href="/plants?query=fruits">Fruits</a>
            <a class="dropdown-item" href="/plants?query=aromates">Aromates</a>
            <a class="dropdown-item" href="/plants">Voir tout</a>
          </div>
        </li>
        <li class="nav-item active">
          <%= link_to "Calendrier", "/calendrier##{Date.today.day}", class: 'nav-link text-white' %>
        </li>
        <li class="nav-item active" style='min-width:88px;'>
          <%= link_to "À propos", a_propos_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", posts_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item" style='min-width:110px;'>
          <%= link_to "Plant Finder", plant_finder_path, class: 'nav-link text-white' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown d-xl-none">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon profil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user.role == "admin" %>
                <%= link_to "Ajouter un article", new_post_path, class: "dropdown-item" %>
                <%= link_to "Mes listes", lists_path, class: "dropdown-item" %>
                <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Mes listes", lists_path, class: "dropdown-item" %>
                <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" style='min-width:110px;'>
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link text-white d-xl-none" %>
          </li>
        <% end %>
        <li class="nav-item" style='min-width:110px;'>
          <%= form_with url: plants_path, method: :get, class: "d-xl-none mb-3 search-form" do %>
            <div class="">
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                style:'max-width:220px; border-radius: 10px;',
                placeholder: "Rechercher une plante"
              %>
            </div>
          <% end %>
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-center bg-success" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto d-flex flex-row-reverse" style="width: 350px;">
        <% if user_signed_in? %>
          <li class="nav-item dropdown d-none d-lg-block d-xl-block">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.variant(resize_to_fill: [40, 40]), class: "avatar", style: "width:40px; height:40px; object-fit:cover;", alt: "User avatar" %>
              <% else %>
                <%= image_tag "https://www.tomlejardinier.com/img/tomlejardinier-pres-3.jpg", class: "avatar", style: "width:40px; height:40px; object-fit:cover;", alt: "Default avatar" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.admin? %>
                <%= link_to "Ajouter un article", new_post_path, class: "dropdown-item" %>
                <%= link_to "Mes listes", lists_path, class: "dropdown-item" %>
                <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Mes listes", lists_path, class: "dropdown-item" %>
                <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
          <div class="me-2 search-container">
            <%= form_with url: plants_path, method: :get, class: "search-form d-none d-xl-block" do %>
              <div class="form-group has-feedback position-relative">
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control search-input",
                  placeholder: "Rechercher"
                %>
                <%= '<span class="form-control-feedback search-icon"><i class="fa-solid fa-magnifying-glass" style="color: #0c4b36; background-color: white;"></i></span>'.html_safe %>
              </div>
            <% end %>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link text-white d-none d-xl-block" %>
          </li>
          <div class="me-2 search-container">
            <%= form_with url: plants_path, method: :get, class: "search-form d-none d-xl-block" do %>
              <div class="form-group has-feedback position-relative">
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control search-input",
                  placeholder: "Rechercher"
                %>
                <%= '<span class="form-control-feedback search-icon"><i class="fa-solid fa-magnifying-glass" style="color: #0c4b36; background-color: white;"></i></span>'.html_safe %>
              </div>
            <% end %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>