config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Routes for Posts
  resources :posts do
    # Nested routes for Comments under Posts
    resources :comments, only: [:create, :update] do
      member do
        get 'edit_comment'
        patch 'update_comment'
      end
    end
  end

  resources :comments, only: :destroy

  resources :contact, only: [:new, :create]

  # Routes for Plants
  resources :plants do
    # Nested routes for Tips under Plant
    resources :tips, only: [:create] do
      member do
        get 'edit_tip'
        patch 'update_tip'
      end
    end
    resources :neighbours, only: [:create]
  end

  # Routes for Lists
  resources :lists do
    # Nested routes for PlantLists under Lists
    resources :plant_lists, only: [:create] do
      member do
        get 'edit_plant_list'
        patch 'update_plant_list'
      end
    end
  end

  # Routes for Tips (outside the nested context if needed)
  resources :tips, only: [:index, :show, :update, :destroy]
  # Routes for PlantLists (outside the nested context if needed)
  resources :plant_lists, only: [:index, :show, :update, :destroy]
  # Routes for Neighbours
  resources :neighbours, only: [:index, :show, :update, :destroy]

  root to: "pages#home"

  get 'a-propos', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  get 'recrutement', to: 'pages#recrutement'
  get 'calendrier', to: 'calendriers#index'
  get 'telecharger', to: 'calendriers#download'
  get 'mentions-legales', to: 'pages#mentions_legales'
  get 'plant-finder', to: 'pages#plant_finder'

end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :tips
  has_many :lists, through: :plant_lists
  has_many :neighbours
  has_many_attached :photos

  include PgSearch::Model

  pg_search_scope :search_by_name_and_description,
                  against: [:name, :categorie],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show]

  def index
    @plants = Plant.all
    @plants = @plants.where(categorie: params[:categorie]) if params[:categorie].present?
    @plants = @plants.where("type_semis ILIKE ?", "%#{params[:type_semis]}%") if params[:type_semis].present?
    @plants = @plants.where("periode_semis ILIKE ?", "%#{params[:periode_semis]}%") if params[:periode_semis].present?
    @plants = @plants.where("periode_recoltes ILIKE ?", "%#{params[:periode_recoltes]}%") if params[:periode_recoltes].present?
    @plants = @plants.where("culture ILIKE ?", "%#{params[:culture]}%") if params[:culture].present?
    @plants = @plants.where(besoin_eau: params[:besoin_eau]) if params[:besoin_eau].present?
    @plants = @plants.where("qualite_sol ILIKE ?", "%#{params[:qualite_sol]}%") if params[:qualite_sol].present?
    @plants = @plants.where("nature_sol ILIKE ?", "%#{params[:nature_sol]}%") if params[:nature_sol].present?
    @plants = @plants.where(hauteur: params[:hauteur]) if params[:hauteur].present?
    @plants = @plants.where(temperature: params[:temperature]) if params[:temperature].present?
    @plants = @plants.where(difficulte: params[:difficulte]) if params[:difficulte].present?
    if params[:query].present?
      @plants = Plant.search_by_name_and_description(params[:query])
    end
  end

  def show
    @tip = Tip.new
    @tips = Tip.where(plant: @plant)
    @list = List.new
    @lists = List.where(user: current_user)
    @bon_voisin = Neighbour.where(plant_1: @plant)
  end

  def create
    @plant = Plant.new(list_params)
    @plant.save
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:name, :description, :nom_scientifique, :famille, :categorie, :type_semis,
                                  :conseil_semis, :conseil_culture, :periode_semis, :periode_recoltes, :culture,
                                  :exposition, :besoin_eau, :nature_sol, :qualite_sol, :hauteur, :maladie, :ecart_rang,
                                  :temperature, :difficulte, :categorie, :query, photos: [])
  end
end

app/views/plants/_plants.html.erb
 <h2 class="text-center mt-5 mb-2">Résultats(<%= plants.count %>)</h2>
 <div class="cards" style="margin-bottom:250px;">
      <% plants.each do | plant | %>
        <div class="card rounded-3" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); background-color: #daf1df; border-radius:12px;">
          <%= cl_image_tag plant.photos.first.key, :cloud_name => "dzhzzutmq", style: 'height: 250px; width: 100%; object-fit: cover; padding: 16px 16px 0 16px;' %>
          <div class="card-body ">
            <h5 class="card-title"><%= plant.name %></h5>
            <h6 class="card-title"><%= plant.categorie %></h6>
            <p class="card-text text-muted fs-6"><%= plant.description.truncate(75) %></p>
            <div class="d-flex justify-content-center">
              <%= link_to "Voir détails", plant_path(plant), class:"btn btn-success text-white rounded-pill" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

app/views/plants/index.html.erb
 <%= turbo_page_requires_reload %>
<div class="main-container m-auto">
<div id="filtres" class="text-center py-3 m-auto mt-5" style="background-color: #DAF1DF; border-radius: 10px 10px 10px 10px; max-width:76%;" data-controller="reveal" data-reveal-hidden-class="d-none">
<div data-action="click->reveal#toggle">
<h3 class="mb-0">Filtres <i class="fa-solid fa-caret-down"></i></h3>
</div>
<div class="d-none" data-reveal-target="item">
  <%= form_with(url: plants_path, method: :get, class: "d-flex flex-wrap justify-content-center", data: {controller: "filter", turbo_frame: "_top"}, style:"max-width: 75%;") do %>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag "Catégorie" %>
        <%= select_tag :categorie,
              options_for_select(['Fruits', 'Légumes', 'Aromates'],
              selected: params[:categorie]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag :type_semis %>
        <%= select_tag :type_semis,
              options_for_select(['Pleine Terre', 'En godet', 'Pépinière', 'Greffage', 'Bouturage'],
              selected: params[:type_semis]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag :culture %>
        <%= select_tag :culture,
              options_for_select(['Pleine terre', 'En pot'],
              selected: params[:culture]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag "Plantation" %>
        <%= select_tag :periode_semis,
              options_for_select(['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
              selected: params[:periode_semis]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
     <div class="" style="min-width: 150px;">
      <div class="text-muted d-flex flex-column">
        <%= label_tag "Récolte" %>
        <%= select_tag :periode_recoltes,
              options_for_select(['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
              selected: params[:periode_recoltes]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag "Difficulté" %>
        <%= select_tag :difficulte,
              options_for_select(['Facile', 'Moyen', 'Difficile'],
              selected: params[:difficulte]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag :exposition %>
        <%= select_tag :exposition,
              options_for_select(['Plein soleil', 'Ombragée', 'Mi-ombragée', 'Ensoleillée'],
              selected: params[:exposition]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag :besoin_eau %>
        <%= select_tag :besoin_eau,
              options_for_select(['Faible', 'Moyen', 'Fort'],
              selected: params[:besoin_eau]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
        <%= label_tag :hauteur %>
        <%= select_tag :hauteur,
              options_for_select(['10-20 cm', '15-30 cm', '20-30 cm', '20-50 cm', '20-60 cm', '30 cm', '30-40 cm', '30-50 cm', '30-60 cm', '30-90 cm', '40-50 cm', '40-60 cm', '40-80 cm', '50-70 cm', '50-100 cm', '60 cm', '60-80 cm', '60-90 cm', '60-100 cm', '60-120 cm', '80 cm', '80-120 cm', '80-140 cm', '1 m', '1.2', '1-1.5 m', '1.5 m', '1.5-2 m', '1-2 m', '1-3 m', '1.5-3 m', '1-7 m', '1-10 m', '2-3 m', '2-4 m', '2-5 m', '3-4 m', '3-5 m', '3-6 m', '3-10 m', '4-6 m', '4-10 m', '4-12 m', '5-10 m', '6-9 m', '15-20 m', '15-30 m'],
              selected: params[:hauteur]),
              include_blank: true,
              class: 'rounded-3 mx-2',
              data: {action: "change->filter#submit"} %>
      </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
          <%= label_tag "Température" %>
          <%= select_tag :temperature,
                options_for_select(['-10-35°C', '-5°C-20°C', '0-20°C', '10°C', '10-15°C', '10-25°C', '10-30°C', '15°C', '15-20°C', '15-25°C', '15-30°C', '20°C', '20-25°C', '20-30°C', '25-35°C'],
                selected: params[:temperature]),
                include_blank: true,
                class: 'rounded-3 mx-2',
                data: {action: "change->filter#submit"} %>
        </div>
    </div>
    <div class="">
      <div class="text-muted d-flex flex-column">
          <%= label_tag :nature_sol %>
          <%= select_tag :nature_sol,
                options_for_select(['Tout types', 'Drainé', 'Acide', 'Ameubli', 'Riche en humus', 'Argileux', 'Léger', 'Profond', 'Riche', 'Neutre', 'Moyen', 'Frais', 'Humifère', 'Sableuse', 'Calcaire'],
                selected: params[:nature_sol]),
                include_blank: true,
                class: 'rounded-3 mx-2',
                data: {action: "change->filter#submit"} %>
        </div>
    </div>
  <% end %>
</div>
</div>
<div class="d-flex justify-content-center mb-4">
    <%= link_to "Réinitialiser", plants_path, class:"text-white text-decoration-none btn btn-success rounded-pill mt-3", style:"max-width: 120px;" %>
  </div>
<div class="w-75 m-auto">
  <% if @plants.empty? %>
    <p class="text-center fst-italic my-5">Aucune plante associée à votre recherche, essayez d'ajuster la température ou le type de sol !</p>
  <% else %>
    <%= turbo_frame_tag "plants", class: "" do %>
      <%= render "plants", plants: @plants %>
    <% end %>
  <% end %>
</div>

</div>

app/views/plants/show.html.erb
<div class="mx-auto" style="max-width: 1200px; width:80%;">
  <div class="mt-2">
    <%= link_to "< Retour", plants_path, class: "text-decoration-none text-black mb-3" %>
  </div>
  <%= turbo_page_requires_reload %>
  <div class="d-flex justify-content-between align-items-center">
    <div class="left-part">
      <h2><%= @plant.name %></h2>
      <p><%= @plant.categorie %></p>
    </div>

    <div class="btn-group rounded h-25">
      <button class="btn btn-primary btn-sm rounded-pill" data-bs-toggle="modal" data-bs-target="#exampleModal" type="button">
        Ajouter à ma liste
      </button>

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title text-center" id="exampleModalLabel">Mes listes</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <% if user_signed_in? %>
              <div class="modal-body">
                <div class="d-flex flex-column p-2">
                  <% @lists.each do |list| %>
                    <div class="d-flex align-items-center justify-content-between">
                      <%= link_to list.nom, lists_url %>
                      <%= button_to "+", list_plant_lists_url(plant_id: @plant.id, list_id: list.id), class: "fs-2 text-success border-0 bg-transparent text-decoration-none" %>
                    </div>
                  <% end %>
                </div>

                <h4 class="text-center">Créer une liste</h4>
                <%= simple_form_for @list do |f| %>
                  <div class="mb-3">
                    <%= f.label :nom %>
                    <%= f.hidden_field :plant, value: @plant.id %>
                    <%= f.text_field :nom, class: "form-control" %>
                  </div>
                  <div class="d-flex justify-content-center">
                    <%= f.button :submit, "Créer", class: "mb-2 text-decoration-none btn btn-success rounded-pill" %>
                  </div>
                <% end %>
              </div>
            <% else %>
              <div class="d-flex justify-content-center align-items-center flex-column py-5">
                <p>Connectez-vous pour ajouter ou créer votre liste</p>
                <button class="btn btn-primary rounded-pill">
                  <a class="text-decoration-none text-white" href="/users/sign_in">Se connecter</a>
                </button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= cl_image_tag @plant.photos.first.key, cloud_name: "dzhzzutmq", class: "w-100 rounded-3 mb-3 m-1 object-fit-cover d-block" %>
      </div>
      <% if @plant.photos.second.present? %>
        <div class="carousel-item">
          <%= cl_image_tag @plant.photos.second.key, cloud_name: "dzhzzutmq", class: "w-100 rounded-3 mb-3 m-1 object-fit-cover d-block" %>
        </div>
      <% end %>
      <% if @plant.photos.third.present? %>
        <div class="carousel-item">
            <%= cl_image_tag @plant.photos.third.key, cloud_name: "dzhzzutmq", class: "w-100 rounded-3 mb-3 m-1 object-fit-cover d-block" %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div data-controller="tabs" data-tabs-active-class="bg-warning" data-tabs-default-tab-value="tab1" class="mt-3">
    <div class="flex">
      <button id="tab1" data-tabs-target="btn" data-action="click->tabs#select" class="border-0 rounded-top p-2">Description</button>
      <button id="tab2" data-tabs-target="btn" data-action="click->tabs#select" class="border-0 rounded-top p-2">Détails</button>
      <button id="tab3" data-tabs-target="btn" data-action="click->tabs#select" class="border-0 rounded-top p-2">Maladies</button>
    </div>
    <div data-tabs-target="tab" id="tab1">
      <div class="card mb-3 bg-warning border-0" style="height: auto;">
        <div class="card-body mb-3">
          <div class="lh-sm">
            <p>
              <strong>Nom scientifique:</strong> <%= @plant.nom_scientifique %> <br>
              <i class="fa-brands fa-pagelines me-3" title="Famille" style="width: 20px; text-align: center;"></i><%= @plant.famille %> <br>
              <i class="fa-solid fa-star-half-stroke me-3" title="Difficulté" style="width: 20px; text-align: center;"></i><%= @plant.difficulte %>
            </p>
          </div>
          <p><%= @plant.description %></p>
          <p><strong>Conseils de semis:</strong> <%= @plant.conseil_semis %></p>
          <p><strong>Conseils de culture:</strong> <%= @plant.conseil_culture %></p>
        </div>
      </div>
    </div>
    <div data-tabs-target="tab" id="tab2">
      <div class="card mb-3 bg-warning border-0" style="height: 400px;">
        <div class="card-body mb-3 lh-base">
          <p>
            <i class="fa-solid fa-seedling me-3" title="Types de semis" style="width: 20px; text-align: center;"></i><%= @plant.type_semis %><br>
            <i class="fa-regular fa-calendar-plus me-3" title="Periode de semis" style="width: 20px; text-align: center;"></i><%= @plant.periode_semis %><br>
            <i class="fa-regular fa-calendar-check me-3" title="Récoltes" style="width: 20px; text-align: center;"></i><%= @plant.periode_recoltes %><br>
            <i class="fa-solid fa-cloud-sun me-3" title="Exposition" style="width: 20px; text-align: center;"></i><%= @plant.exposition %><br>
            <i class="fa-solid fa-droplet me-3" title="Besoin en eau" style="width: 20px; text-align: center;"></i><%= @plant.besoin_eau %><br>
            <i class="fa-solid fa-arrow-up me-3" title="Hauteur" style="width: 20px; text-align: center;"></i><%= @plant.hauteur %> <br>
            <i class="fa-solid fa-arrows-left-right me-3" title="Ecart entre les plantes" style="width: 20px; text-align: center;"></i><%= @plant.ecart_rang %><br>
            <i class="fa-solid fa-temperature-low me-3" title="Température" style="width: 20px; text-align: center;"></i><%= @plant.temperature %><br>
            <strong>Culture:</strong> <%= @plant.culture %><br>
            <strong>Nature du sol:</strong> <%= @plant.nature_sol %><br>
            <strong>Qualité du sol:</strong> <%= @plant.qualite_sol %><br>
          </p>
        </div>
      </div>
    </div>
    <div data-tabs-target="tab" id="tab3">
      <div class="card mb-3 bg-warning border-0" style="height: 300px;">
        <div class="card-body mb-3">
          <p><strong>Maladies:</strong> <%= @plant.maladie %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="test-1" data-edit-tip-target="messages" >
    <h5 class="d-flex flex-row">
      <i class="fa-regular fa-pen-to-square"></i>
      <span class="text-decoration-underline ms-2">Conseils des jardiniers :</span>
    </h5>
    <div class="row">
  <!-- Section pour les conseils -->
      <div class="col-md-12">
        <% if @plant.tips.present? %>
          <% @plant.tips.each do |tip| %>
            <div class="card mb-3 p-3" style="background-color: #f0fff4;" id="tip-<%= tip.id %>">
              <div class="card-body">
                <div class="tip-content" data-controller="edit-tip">
                  <div>
                    <strong>Par <%= tip.user.prenom %> <%= tip.user.nom %> :</strong>
                  </div>
                  <p class="text-decoration-underline fst-italic"><%= tip.titre %></p>
                  <p><%= tip.contenu %></p>
                  <% if tip.user == current_user %>

                    <div class="d-flex justify-content-end">
                      <%= link_to  edit_tip_plant_tip_path(plant_id: @plant, tip: tip),  data: {action: "click->edit-tip#toggle"}, class: 'btn btn-success text-white rounded-pill me-2 edit-tip-btn', title: "Modifier" do %>
                        <i class="fa-solid fa-pen"></i>
                      <% end %>
                      <%= link_to tip_path(tip), data: {
                        turbo_method: :delete,
                        turbo_confirm: 'Are you sure?',
                        controller: "delete-alert",
                        delete_alert_icon_value: "warning",
                        delete_alert_title_value: "Êtes vous sur ?",
                        delete_alert_html_value: "Supprimer.",
                        delete_alert_confirm_button_text_value: "Oui",
                        delete_alert_cancel_button_text_value: "Non",
                        action: "click->delete-alert#confirmDelete",
                        turbo: false
                      }, class: 'btn btn-success text-white rounded-pill', title: "Supprimer" do %>
                        <i class="fa-solid fa-trash"></i>
                        <% end %>
                      </div>
                    <div class="tip-edit-form d-none" data-edit-tip-target="form">
                      <%= simple_form_for [@plant, tip], url: update_tip_plant_tip_path(plant_id: @plant, tip_id: tip, id:tip.id), method: :patch,  html: { class: 'edit-tip-form' } do |f| %>
                        <%= f.input :titre, input_html: { value: tip.titre } %>
                        <%= f.input :contenu, input_html: { value: tip.contenu } %>
                        <div class="d-flex justify-content-end">
                          <%= f.submit "Mettre à jour", class: 'btn btn-secondary text-white rounded-pill mx-auto' %>
                        </div>
                    <% end %>
                </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="fst-italic p-3 d-flex flex-column align-items-center justify-content-center rounded mb-3" style="background-color: #f0fff4;">Aucun conseil pour le moment.</p>
        <% end %>
      </div>
    </div>
  </div>


  <% if user_signed_in? %>
  <div class="card p-3 m-auto mb-5" style="background-color: #f0fff4;">
    <h4 class="text-center">Ajouter votre conseil</h4>
    <%= simple_form_for([@plant, @tip],   html: { id: 'new-comment-form', label: false, data: { controller: "alert",
      alert_icon_value: "success",
      alert_title_value: "Astuce ajouté avec succès",
      confirm_button_text: "All good!",
      confirmButtonColor: "#0c4b36",
      show_cancel_button: true,
      action: "submit->alert#initSweetalert",
      turbo: false }}) do |f| %>
      <%= f.input :titre, label: false, placeholder: "Entrez le titre ici" %>
      <%= f.input :contenu, label: false, placeholder: "Entrez le contenu ici" %>
      <div class="d-flex justify-content-end">
        <%= f.submit "Publier", class: "btn btn-success text-white w-25 rounded-pill" %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="p-3 d-flex flex-column align-items-center justify-content-center rounded mb-5" style="background-color: #daf1df;">
    <p>Connectez-vous pour ajouter vos conseils !</p>
    <button class="btn btn-primary rounded-pill">
      <a class="text-decoration-none text-white " href="/users/sign_in">Se connecter</a>
    </button>
  </div>
<% end %>


  <div class="mb-5 bg-success p-3 text-white rounded">
    <h3 class="text-center">Bon voisins</h3>
  </div>

  <div class="cards mt-3" style="margin-bottom:300px;">
    <% @bon_voisin.each do |bon_voisin| %>
      <div class="card rounded-3" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); background-color: #daf1df; border-radius: 12px;">
        <%= cl_image_tag bon_voisin.plant_2.photos.first.key, cloud_name: "dzhzzutmq", style: 'height: 250px; width: 100%; object-fit: cover; padding: 16px 16px 0 16px;' %>
        <div class="card-body">
          <h5 class="card-title"><%= bon_voisin.plant_2.name %></h5>
          <h6 class="card-title"><%= bon_voisin.plant_2.categorie %></h6>
          <p class="card-text text-muted fs-6"><%= bon_voisin.plant_2.description.truncate(65) %></p>
          <div class="d-flex justify-content-center">
            <%= link_to "Voir détails", plant_path(bon_voisin.plant_2), class: "btn btn-success text-white rounded-pill" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>