config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Routes for Posts
  resources :posts do
    # Nested routes for Comments under Posts
    resources :comments, only: [:create, :update] do
      member do
        get 'edit_comment'
        patch 'update_comment'
      end
    end
  end

  resources :comments, only: :destroy

  resources :contact, only: [:new, :create]

  # Routes for Plants
  resources :plants do
    # Nested routes for Tips under Plant
    resources :tips, only: [:create] do
      member do
        get 'edit_tip'
        patch 'update_tip'
      end
    end
    resources :neighbours, only: [:create]
  end

  # Routes for Lists
  resources :lists do
    # Nested routes for PlantLists under Lists
    resources :plant_lists, only: [:create] do
      member do
        get 'edit_plant_list'
        patch 'update_plant_list'
      end
    end
  end

  # Routes for Tips (outside the nested context if needed)
  resources :tips, only: [:index, :show, :update, :destroy]
  # Routes for PlantLists (outside the nested context if needed)
  resources :plant_lists, only: [:index, :show, :update, :destroy]
  # Routes for Neighbours
  resources :neighbours, only: [:index, :show, :update, :destroy]

  root to: "pages#home"

  get 'a-propos', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  get 'recrutement', to: 'pages#recrutement'
  get 'calendrier', to: 'calendriers#index'
  get 'telecharger', to: 'calendriers#download'
  get 'mentions-legales', to: 'pages#mentions_legales'
  get 'plant-finder', to: 'pages#plant_finder'

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_rich_text :rich_body
  has_one_attached :photo

  validates :titre, presence: true
  validates :titre, length: { maximum: 255 }
  validates :contenu, length: { maximum: 100000 }

  extend FriendlyId
  friendly_id :titre, use: :slugged

  include PgSearch::Model
  pg_search_scope :search_by_titre_and_contenu_and_categorie,
                  against: [:titre, :contenu, :categorie],
                  using: {
                    tsearch: { prefix: true }
                  }

  def slug
    titre.to_s.parameterize
  end

  def should_generate_new_friendly_id?
    titre_changed?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:edit, :update, :destroy]

  def index
    if params[:query].present?
      @posts = Post.search_by_titre_and_contenu_and_categorie(params[:query])
    else
      @posts = Post.all
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "L'article a bien été ajouté !"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "L'article a bien été modifié !"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "L'article a bien été supprimé !"
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_url, alert: 'Post not found.' # Gérer le cas où le post n'existe pas
  rescue ArgumentError
    redirect_to posts_url, alert: 'Invalid post ID.' # Gérer le cas où l'ID est invalide
  end

  def authorize_admin
    redirect_to posts_url, alert: 'Access denied.' unless current_user&.admin?
  end

  def post_params
    params.require(:post).permit(:titre, :contenu, :rich_body, :categorie, :date_publication, :note, :photo)
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for(post) do |f| %>

  <div class="form-inputs">
    <%= f.input :titre %>
  </div>

  <div class="form-inputs">
    <%= f.input :categorie %>
  </div>

  <div class="form-inputs">
    <%= f.input :date_publication, as: :date, html5: true %>
  </div>

  <div class="form-inputs mb-3">
    <label class="form-label">Contenu</label>
    <%= f.rich_text_area :rich_body, class:" trix-content" %>
  </div>

  <div class="w-50">
  <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions d-flex justify-content-center">
    <%= f.button :submit, "Publier", class:"btn btn-success rounded-pill" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2 class="text-center"> Modification de post ici</h2>
<div class="w-75 m-auto">
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://st.hzcdn.com/simgs/pictures/jardins/bac-pour-jardins-cote-jardin-et-clotures-img~8161e8c40659c718_14-1284-1-8ca4e4f.jpg); padding-bottom: 64px; background-size: cover; background-position: center">
  <div class="container">
    <h1 style="text-align: center;">When To Plant 🌱</h1>
    <h3 style="text-align: center;">Le Blog</h3>
    <p>
      Découvrez notre blog spécialisé sur les fruits, légumes et aromates,
      offrant une mine d'informations sur leur culture, leurs bienfaits et des conseils précieux pour réussir votre jardin potager à chaque saison."
    </p>
  </div>
</div>

<div class="container mb-5 pb-5">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h2 class="mb-4 mt-1 text-center">Articles récents</h2>

      <!-- Search Bar -->
      <div class="mb-4">
        <div class="container mt-4 py-3" style="background-color: #DAF1DF; border-radius:10px;">
          <div class="row justify-content-center">
            <div class="col-12 col-md-8">
              <%= form_with url: posts_path, method: :get, class: "d-flex w-100" do %>
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control flex-grow-1 me-2 rounded-pill",
                  placeholder: "Recherche un article" %>
                <%= submit_tag "Rechercher", class: "btn btn-success text-white rounded-pill" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <!-- Articles show -->
      <div id="articles">
        <% @posts.each_slice(2).with_index do |post_pair, row_index| %>
          <div class="row justify-content-between mb-3 <%= 'mb-5' if row_index == @posts.each_slice(2).count - 1 %>">
            <% post_pair.each do |post| %>
              <div class="col-12 col-md-5 mb-3">
                <div class="card article-card mb-5" style="background-color: #f0fff4; width: 100%;">
                  <div class="card-body">
                    <% if post.photo.present? && post.photo.key.present? %>
                      <%= cl_image_tag post.photo.key, alt: post.titre, style: "height: 200px; width: 100%; object-fit: cover; border-radius:10px;" %>
                    <% else %>
                      <%= image_tag "default_image.png", style: "height: 250px; width: 100%; object-fit: cover; padding: 16px 16px 0 16px;" %>
                    <% end %>
                    <h3 class="card-title"><%= post.titre %></h3>
                    <h5 class="card-subtitle mb-2 text-muted"><%= post.categorie %></h5>
                    <p class="card-text"><%= post.rich_body.to_plain_text.truncate(200) %></p>
                    <div class="d-flex justify-content-end">
                      <%= link_to "Lire l'article", post_path(post), class: 'btn btn-success text-white rounded-pill', style: 'background-color: #0C4B36;' %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %> <!-- Fermer le bloc each_slice -->
      </div> <!-- Fermer la div #articles -->
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">Ajouter un nouvel article</h1>
<div class="w-75 m-auto">
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="container mt-5" style="margin-bottom:200px;">
  <div class="row">
  <!-- Colonne pour l'article -->
  <div class="col-md-12">
    <div class="card mb-5" style="background-color: #f0fff4;">
      <div class="card-body">
        <% if @post.photo.present? && @post.photo.key.present? %>
          <%= cl_image_tag @post.photo.key, alt: @post.titre, style: "height: 300px; width: 100%; object-fit: cover; border-radius:10px;" %>
        <% else %>
          <%= image_tag "default_image.png", alt: @post.titre, style: "height: 300px; width: 100%; object-fit: cover; border-radius:10px;" %>
        <% end %>
        <h1 class="card-title mt-1"><%= @post.titre %></h1>
        <h5 class="card-subtitle mb-2 text-muted"><%= @post.categorie %></h5>
        <p class="card-text"><small class="text-muted"><%= @post.date_publication %></small></p>
        <p class="card-text"><%= @post.rich_body %></p>

        <% if current_user&.admin? %>
          <div class="d-flex justify-content-end mt-5 mb-3">
            <%= link_to 'Modifier', edit_post_path(@post), class: 'btn btn-primary text-white rounded-pill mr-2 me-3', title: "Modifier" %>
            <%= link_to 'Supprimer', post_path(@post), data: {
                        turbo_method: :delete,
                        turbo_confirm: 'Are you sure?',
                        controller: "delete-alert",
                        delete_alert_icon_value: "warning",
                        delete_alert_title_value: "Êtes vous sur ?",
                        delete_alert_html_value: "Supprimer.",
                        delete_alert_confirm_button_text_value: "Oui",
                        delete_alert_cancel_button_text_value: "Non",
                        action: "click->delete-alert#confirmDelete",
                        turbo: false
                      }, class: 'btn btn-success text-white rounded-pill mr-2 me-3', title: "Supprimer" %>
          </div>
        <% end %>
        <div class="d-flex justify-content-end mt-5 mb-3">
          <%= link_to 'Retour', posts_path, class: 'btn btn-success text-white rounded-pill me-3' %>
        </div>
      </div>
    </div>
  </div>
</div>


  <div class="row">
    <!-- Section pour les commentaires -->
    <div class="col-md-12">
      <% if @post.comments.present? %>
        <% @post.comments.each do |comment| %>
          <div class="card mb-3 p-3" style="background-color: #f0fff4;" id="comment-<%= comment.id %>">
            <div class="card-body">
              <div class="comment-content">
                <div>
                  <strong>Par <%= comment.user.prenom %> <%= comment.user.nom %> :</strong>
                </div>
                <p class="text-decoration-underline fst-italic"><%= comment.titre %></p>
                <p><%= comment.contenu %></p>
                <% if comment.user == current_user %>
                  <div class="d-flex justify-content-end">
                    <button class="btn btn-success text-white rounded-pill mr-2 edit-comment-btn me-2" data-comment-id="<%= comment.id %>">Modifier</button>
                    <%= link_to 'Supprimer', comment_path(comment), data: {
                        turbo_method: :delete,
                        turbo_confirm: 'Are you sure?',
                        controller: "delete-alert",
                        delete_alert_icon_value: "warning",
                        delete_alert_title_value: "Êtes vous sur ?",
                        delete_alert_html_value: "Supprimer.",
                        delete_alert_confirm_button_text_value: "Oui",
                        delete_alert_cancel_button_text_value: "Non",
                        action: "click->delete-alert#confirmDelete",
                        turbo: false
                      }, class: 'btn btn-success text-white rounded-pill' %>
                  </div>
                <% end %>
              </div>
              <div class="comment-edit-form d-none">
                <%= simple_form_for [@post, comment], url: update_comment_post_comment_path(@post, comment), method: :patch, html: { class: 'edit-comment-form' } do |f| %>
                  <%= f.input :titre, input_html: { value: comment.titre } %>
                  <%= f.input :contenu, input_html: { value: comment.contenu } %>
                  <div class="d-flex justify-content-end">
                    <%= f.submit "Mettre à jour", class: 'btn btn-secondary text-white rounded-pill mx-auto' %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="fst-italic p-3 d-flex flex-column align-items-center justify-content-center rounded mb-3" style="background-color: #f0fff4;">Aucun commentaire pour le moment.</p>
      <% end %>
    </div>
  </div>

  <!-- Section pour ajouter un commentaire -->
  <div class="row mt-4">
    <div class="col-md-12">
      <div class="card mb-5 p-3" style="background-color: #f0fff4;">
        <div class="card-body">
          <h2>Ajouter un Commentaire</h2>
          <%= simple_form_for [@post, Comment.new], html: { id: 'new-comment-form', data: { controller: "alert",
            alert_icon_value: "success",
            alert_title_value: "Commentaire ajouté avec succès",
            confirm_button_text: "All good!",
            confirmButtonColor: "#0c4b36",
            show_cancel_button: true,
            action: "submit->alert#initSweetalert" } } do |f| %>
            <%= f.input :titre, label: false, placeholder: "Entrez le titre ici" %>
            <%= f.input :contenu, label: false, placeholder: "Entrez le contenu ici" %>
            <div class="d-flex justify-content-end">
              <%= f.submit "Soumettre", class: 'btn btn-success text-white rounded-pill' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>